@server = http://localhost:4004
# @me = Authorization: Basic {{$processEnv USER}}:

# For Node.js (cds watch)

### ------------------------------------------------------------------------
# Get Metadata
GET http://localhost:4004/catalog/$metadata

### ------------------------------------------------------------------------
POST http://localhost:4004/catalog/SalesOrders
Content-Type: application/json;IEEE754Compatible=true
# Authorization: Basic alice:

{
  "name": "SO Hello 2",
  "description": "This is a sample SO created by http test"
}

# For Java app

### ------------------------------------------------------------------------
POST http://localhost:8080/odata/v4/CatalogService/SalesOrders
Content-Type: application/json;IEEE754Compatible=true
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "SO Hello 2",
  "description": "This is a sample SO created by http test"
}